### ISSUE TITLE
[Error] No disparity Images and synchronized triplets in 'image_view' 

### ISSUE THREAD

**Issue by Mdmorshadurrahman** [strawlab/image_pipeline#1]
Receiving images from both the cameras but not getting disparity images as well as synchronized triplets. 

rosrun image_view stereo_view stereo:=/stereo image:=image_rect _approReceiving images from both the cameras but not getting disparity images as well as synchronized triplets. 

rosrun image_view stereo_view stereo:=/stereo image:=image_rect _approximate_sync:=True _queue_size:=2000
[ INFO] [1648727963.521988615]: Subscribing to:
	* /stereo/left/image_rect
	* /stereo/right/image_rect
	* /stereo/disparity
[ WARN] [1648727978.592653685]: [stereo_view] Low number of synchronized left/right/disparity triplets received.
Left images received:      217 (topic '/stereo/left/image_rect')
Right images received:     218 (topic '/stereo/right/image_rect')
Disparity images received: 0 (topic '/stereo/disparity')
Synchronized triplets: 0
Possible issues:
	* stereo_image_proc is not running.
	  Does `rosnode info /stereo_view_1648727963390661294` show any connections?
	* The cameras are not synchronized.
	  Try restarting stereo_view with parameter _approximate_sync:=True
	* The network is too slow. One or more images are dropped from each triplet.
	  Try restarting stereo_view, increasing parameter 'queue_size' (currently 2000)
[ WARN] [1648727993.592497204]: [stereo_view] Low number of synchronized left/right/disparity triplets received.

checked with rqt_graph which seem ok 
![image](https://user-images.githubusercontent.com/65698541/161057847-7add35a0-7ff4-4a53-b9bf-919faf23b2b1.png)

even, checked with rosnode info /stereo_view_1648727963390661294 this command and it shows:
Publications: 
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /stereo/disparity [stereo_msgs/DisparityImage]
 * /stereo/left/image_mono [sensor_msgs/Image]
 * /stereo/right/image_mono [sensor_msgs/Image]

Services: 
 * /stereo_view_1648723258293586411/get_loggers
 * /stereo_view_1648723258293586411/set_logger_level

contacting node http://192.168.7.166:36901/ ...
Pid: 6345
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound (53323 - 192.168.7.201:33676) [14]
    * transport: TCPROS
 * topic: /stereo/left/image_mono
    * to: /stereo/stereo_image_proc (http://192.168.7.166:38357/)
    * direction: inbound (37282 - 192.168.7.166:58649) [23]
    * transport: TCPROS
 * topic: /stereo/right/image_mono
    * to: /stereo/stereo_image_proc (http://192.168.7.166:38357/)
    * direction: inbound (37278 - 192.168.7.166:58649) [21]
    * transport: TCPROS
 * topic: /stereo/disparity
    * to: /stereo/stereo_image_proc (http://192.168.7.166:38357/)
    * direction: inbound (37280 - 192.168.7.166:58649) [22]
    * transport: TCPROS

my stereo_image_proc.launch file :

<launch>

  <arg name="manager" /> 
  <arg name="respawn" default="false" />
  <arg name="left" default="left" />
  <arg name="right" default="right" />
 # <arg name="downsampling_factor" value="1" />
  <arg name="approximate_sync" default="true" />
  #<arg name="enable_pointcloud" default="true"/>
  #<arg name="pointcloud_texture_stream" default="RS2_STREAM_COLOR"/>
  #<arg name="pointcloud_texture_index" default="0"/>

  <arg     if="$(arg respawn)" name="bond" value="" />
  <arg unless="$(arg respawn)" name="bond" value="--no-bond" />

  
  <include file="$(find image_proc)/launch/image_proc.launch"
           ns="$(arg left)">
    <arg name="manager" value="/pipeline" />
    <arg name="approximate_sync" default="true" />
    <arg name="respawn" value="$(arg respawn)" />
  </include>

  
  <include file="$(find image_proc)/launch/image_proc.launch"
           ns="$(arg right)">
    <arg name="manager" value="/pipeline" />
    <arg name="approximate_sync" default="true" />
    <arg name="respawn" value="$(arg respawn)" />
  </include>

  
  <node pkg="nodelet" type="nodelet" name="disparity"
        args="load stereo_image_proc/disparity $(arg manager) $(arg bond)"
        respawn="$(arg respawn)" >
    <param name="approximate_sync" value="True" />
  </node>

  
  <node pkg="nodelet" type="nodelet" name="point_cloud2"
        args="load stereo_image_proc/point_cloud2 $(arg manager) $(arg bond)"
        respawn="$(arg respawn)" >
    <param name="approximate_sync" value="True" />
  </node>
</launch>

**Comment by astraw** [comment]
This repository is not the "source" of image_pipeline and I think you would be better off to file your issue there. I will close this as "Won't Fix" because we are not using this software anymore. I should also archive the repository.
